name: homelab-media-stack

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: homelab-media-jellyfin
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./config/jellyfin:/config
      - ./media:/data:ro
    ports:
      - ${UI_BIND_ADDRESS}:${JELLYFIN_PORT}:8096
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: homelab-media-qbittorrent
    profiles: ["automation"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: ${QBITTORRENT_PORT}
    volumes:
      - ./config/qbittorrent:/config
      - ./media:/data
    ports:
      - ${UI_BIND_ADDRESS}:${QBITTORRENT_PORT}:${QBITTORRENT_PORT}
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: homelab-media-prowlarr
    profiles: ["automation"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./config/prowlarr:/config
    ports:
      - ${UI_BIND_ADDRESS}:${PROWLARR_PORT}:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: homelab-media-sonarr
    profiles: ["automation"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./config/sonarr:/config
      - ./media:/data
    ports:
      - ${UI_BIND_ADDRESS}:${SONARR_PORT}:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: homelab-media-radarr
    profiles: ["automation"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./config/radarr:/config
      - ./media:/data
    ports:
      - ${UI_BIND_ADDRESS}:${RADARR_PORT}:7878
    restart: unless-stopped
